apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tfReplicaSpecs:
                type: object
                properties:
                  Chief:
                    type: object
                    properties:
                      replicas:
                        maximum: 1
                        minimum: 1
                        type: integer
                  PS:
                    type: object
                    properties:
                      replicas:
                        minimum: 1
                        type: integer
                  Worker:
                    type: object
                    properties:
                      replicas:
                        minimum: 1
                        type: integer
                  Evaluator:
                    type: object
                    properties:
                      replicas:
                        minimum: 0
                        type: integer
    additionalPrinterColumns:
    - jsonPath: .status.conditions[-1:].type
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
